# Generated by Django 3.2.2 on 2021-05-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_Us',
            fields=[
                ('about_us_paragraph', models.TextField(help_text='Enter about us here', primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'about us',
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='About_Us_arabic',
            fields=[
                ('about_us_paragraph_arabic', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'about us',
                'verbose_name_plural': 'About Us (Arabic)',
            },
        ),
        migrations.CreateModel(
            name='AskConsultant',
            fields=[
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('file_number', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='File Number')),
                ('inquiry', models.TextField(verbose_name='Inquiry')),
            ],
            options={
                'verbose_name': 'inquiry',
                'verbose_name_plural': 'Inquiries',
            },
        ),
        migrations.CreateModel(
            name='AskConsultant_arabic',
            fields=[
                ('name_arabic', models.CharField(max_length=100, verbose_name='Name')),
                ('file_number_arabic', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='File Number')),
                ('inquiry_arabic', models.TextField(verbose_name='Inquiry')),
            ],
            options={
                'verbose_name': 'inquiry in arabic',
                'verbose_name_plural': 'Inquiries (Arabic)',
            },
        ),
        migrations.CreateModel(
            name='link_keyword',
            fields=[
                ('keyword_values', models.CharField(primary_key=True, help_text='Enter keyword here', max_length=100, verbose_name='Keyword')),
                ('keyword_values_arabic', models.CharField(default='', help_text='Enter keyword in arabic here', max_length=100, verbose_name='Arabic Keyword')),
                ('links', models.CharField(help_text='Enter corresponding link here', max_length=1000, verbose_name='Link')),
            ],
            options={
                'verbose_name': 'keyword and link',
                'verbose_name_plural': 'Keywords and Links',
            },
        ),
        migrations.CreateModel(
            name='manual_response',
            fields=[
                ('new_keyword', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Non-Database Keyword')),
                ('admin_data', models.TextField(verbose_name='Admin Response')),
                ('email_id', models.EmailField(default='', max_length=254, verbose_name='Added By')),
            ],
            options={
                'verbose_name': 'manual response',
                'verbose_name_plural': 'Manual Responses',
            },
        ),
        migrations.CreateModel(
            name='manual_response_arabic',
            fields=[
                ('new_keyword_arabic', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Non-Database Keyword')),
                ('admin_data_arabic', models.TextField(verbose_name='Admin Response')),
                ('email_id_arabic', models.EmailField(default='', max_length=254, verbose_name='Added By')),
            ],
            options={
                'verbose_name': 'arabic manual response',
                'verbose_name_plural': 'Manual Responses (Arabic)',
            },
        ),
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='text_keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_value', models.TextField(help_text='Enter keyword here', verbose_name='Keyword')),
                ('desc', models.TextField(help_text='Enter corresponding response here', verbose_name='Intent')),
            ],
            options={
                'verbose_name': 'keyword and intent',
                'verbose_name_plural': 'Keywords and Intents',
            },
        ),
        migrations.CreateModel(
            name='text_keyword_arabic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_value_arabic', models.CharField(help_text='Enter keyword here', max_length=100, verbose_name='Keyword')),
                ('desc_arabic', models.TextField(help_text='Enter corresponding response here', verbose_name='Intent')),
            ],
            options={
                'verbose_name': 'arabic keyword and intent',
                'verbose_name_plural': 'Keywords and Intents (Arabic)',
            },
        ),
    ]
