# Generated by Django 3.2.2 on 2021-05-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='text_keyword',
            options={'verbose_name': 'question and intent', 'verbose_name_plural': 'Questions and Intents'},
        ),
        migrations.AlterModelOptions(
            name='text_keyword_arabic',
            options={'verbose_name': 'arabic question and intent', 'verbose_name_plural': 'Questions and Intents (Arabic)'},
        ),
        migrations.AlterField(
            model_name='text_keyword',
            name='keyword_value',
            field=models.TextField(help_text='Enter question here', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='text_keyword_arabic',
            name='keyword_value_arabic',
            field=models.CharField(help_text='Enter question here', max_length=100, verbose_name='Question'),
        ),
    ]
