# Generated by Django 3.2.4 on 2021-07-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotApp', '0002_auto_20210514_1654'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Msg',
        ),
        migrations.AddField(
            model_name='text_keyword',
            name='tag',
            field=models.CharField(choices=[('Academic Accreditation', (('cat_1.1', 'Cat 1.1'), ('cat_1.2', 'Cat 1.2'))), ('EQAUP', (('cat_2.1', 'Cat 2.1'), ('cat_2.2', 'Cat 2.2'))), ('Estebanh', (('cat_3.1', 'Cat 3.1'), ('cat_3.2', 'Cat 3.2'))), ('Quality', (('cat_4.1', 'Cat 4.1'), ('cat_4.2', 'Cat 4.2'))), ('Training', (('cat_5.1', 'Cat 5.1'), ('cat_5.2', 'Cat 5.2'))), ('Domain', (('cat_6.1', 'Cat 6.1'), ('cat_6.2', 'Cat 6.2'))), ('noanswer', (('cat_none1', 'Cat None 1'), ('cat_none2', 'Cat None 2')))], default='cat_none1', max_length=20),
        ),
    ]
