# Generated by Django 3.1.7 on 2021-07-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotApp', '0003_auto_20210706_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text_keyword',
            name='id',
        ),
        migrations.RemoveField(
            model_name='text_keyword_arabic',
            name='id',
        ),
        migrations.AlterField(
            model_name='text_keyword',
            name='keyword_value',
            field=models.TextField(help_text='Enter question here', primary_key=True, serialize=False, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='text_keyword',
            name='tag',
            field=models.CharField(choices=[('academic_accreditation', 'Academic Accreditation'), ('eqaup', 'EQAUP'), ('estabanh', 'Estabanh'), ('quality', 'Quality'), ('training', 'Training'), ('domain', 'Domain'), ('noanswer', 'No Answer')], default='cat_none1', max_length=100),
        ),
        migrations.AlterField(
            model_name='text_keyword_arabic',
            name='keyword_value_arabic',
            field=models.CharField(help_text='Enter question here', max_length=100, primary_key=True, serialize=False, verbose_name='Question'),
        ),
    ]
