# Generated by Django 3.2.4 on 2021-07-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotApp', '0004_auto_20210708_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='arabic_links_manual_response',
            fields=[
                ('new_topic_arabic', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='New Topic')),
                ('admin_data', models.TextField(verbose_name='Admin Response')),
                ('email_id_arabic', models.EmailField(default='', max_length=254, verbose_name='Added By')),
            ],
            options={
                'verbose_name': 'manual response to arabic link',
                'verbose_name_plural': 'Manual Responses to Arabic Links',
            },
        ),
        migrations.CreateModel(
            name='links_manual_response',
            fields=[
                ('new_topic', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='New Topic')),
                ('admin_data', models.TextField(verbose_name='Admin Response')),
                ('email_id', models.EmailField(default='', max_length=254, verbose_name='Added By')),
            ],
            options={
                'verbose_name': 'manual response to link',
                'verbose_name_plural': 'Manual Responses to Links',
            },
        ),
        migrations.AlterField(
            model_name='link_keyword',
            name='links',
            field=models.TextField(help_text='Enter corresponding link here', max_length=1000, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='text_keyword',
            name='tag',
            field=models.TextField(help_text='Enter corresponding unique tag here', max_length=100, verbose_name='Tag'),
        ),
    ]
